project:
  type: website
  output-dir: docs

website:
  title: "R Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bài 1.qmd
      - bài 2.qmd
      - bài 3.qmd
      - Bài 4.qmd
      - bài 5.qmd
      - bài 6.qmd
      - bài 7.qmd
      - bài 8.qmd
      - bài 9.qmd
      - bài 10.qmd
      - bài 11.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

